// AUTO-GENERATED by scripts/assign-raw-images.mjs — do not edit manually.
// Run: npm run image:assign
// Last updated: 2026-04-17

export const imageManifest: Record<string, string> = {
  "dinh-duong.hero": "/images/dinh-duong/hero-dinh-duong-thien-lanh.webp",
  "dinh-duong.topic.kien-thuc-nen-tang": "/images/dinh-duong/topics/topic-kien-thuc-nen-tang.png",
  "dinh-duong.topic.chat-dam-hang-ngay": "/images/dinh-duong/topics/topic-chat-dam-hang-ngay.webp",
  "dinh-duong.topic.dai-thao-duong-beo-phi-chuyen-hoa": "/images/dinh-duong/topics/topic-dai-thao-duong-beo-phi-chuyen-hoa.webp",
  "dinh-duong.topic.sua-va-nhung-dieu-thuong-tin": "/images/dinh-duong/topics/topic-sua-va-nhung-dieu-thuong-tin.svg",
  "dinh-duong.hero.sua-wth": "/images/dinh-duong/hero-sua-wth.svg",
  "dinh-duong.topic.ung-thu-va-goc-nhin-tu-bua-an": "/images/dinh-duong/topics/topic-ung-thu-va-goc-nhin-tu-bua-an.webp",
  "ung-xu.hero": "/images/ung-xu/hero-ung-xu-thien-lanh.webp",
  "ung-xu.topic.hieu-minh-de-song-nhe-hon": "/images/ung-xu/topics/topic-hieu-minh-de-song-nhe-hon.webp",
  "ung-xu.topic.loi-noi-va-giao-tiep": "/images/ung-xu/topics/topic-loi-noi-va-giao-tiep.webp",
  "ung-xu.topic.nhung-tinh-huong-de-gap-trong-doi-song": "/images/ung-xu/topics/topic-nhung-tinh-huong-de-gap-trong-doi-song.webp",
};
